# version: '3.8'
# services:
#   postgres:
#     image: postgres:15
#     container_name: postgres_container
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   adminer:
#     image: adminer
#     container_name: adminer_container
#     restart: always
#     ports:
#       - "8080:8080"

# volumes:
#   postgres_data:



